### ISSUE TITLE
Migrating GoMuleR4.4.3_Resurrected_1.0 stash items to GoMuleR4.4.14-BETA_Resurrected_1.0

### ISSUE THREAD

**Issue by Brumpers** [GoMule/GoMule#3]
Thank you to everyone working on this. I can load the empty shared stash (provided on sourceforge) with pre 2.4 GoMule, however I am not able to drop any items into it as expected. I can click on the 3 tabs, but it wont allow any items to be dropped into it. Has anyone else observed this issue, or have another suggested workaround to migrate items? I have about 3k items to migrate. Thank you for your help!

**Comment by ChthonVII** [comment]
I have NOT tested this, but this should work if I'd reading the 2.4 commits correctly:
1. Use pre-2.4 GoMule to move any personalized items out of your .d2x stashes and onto a 2.3 character file.
2. Use a hex editor to change the 6th byte of each .d2x stash from 0x61 to 0x62. You should now be able to load them in 2.4 GoMule.
3. Put the character file with the personalized items into your save directory and let D2R update the character to 2.4. Now you can retrieve the items from it using 2.4 GoMule.

**Comment by Brumpers** [comment]
Option 2 sounds the best... however I am not a coder myself, so I don't know how to do this (I'm just a dummy trying to figure out the best way to migrate thousands of items).
At some point, would it be feasible to create some type of converter (for 2.3 to 2.4 stashes) like the one that was create for D2 legacy to D2R GoMule stashes?
Like the one here? https://pairofdocs.github.io/atma-stash-d2r/convert96to97.html

**Comment by ChthonVII** [comment]
> Option 2 sounds the best... 

Those aren't options; that's an ordered list of steps.

**Comment by silospen** [comment]
Hi, you can see the discussion here: https://sourceforge.net/p/gomule/bugs/27/#c90e

Gomule has never offered any item converters to avoid any issues with loading items in game. The steps provided above may work for items which have the same encoding before and after patch 2.4, the only major change I found was to personalized items, so you'd want to remove them from your stash beforehand.
