### ISSUE TITLE
Patch 2.5 characters are disconnected

### ISSUE THREAD

**Issue by ajgringo619** [GoMule/GoMule#8]
(Also posted here: https://sourceforge.net/p/gomule/bugs/33/. Which is the preferred place to post bug reports?)

Same issue as with the v2.4 patch release. At least this time the patch notes specifically list all of the new/changed text files.

**Comment by silospen** [comment]
Thanks, will take a look.

**Comment by silospen** [comment]
Updated version released, let me know how you get on. Instructions/caveats here: https://www.purediablo.com/forums/threads/gomule-for-d2-resurrected.2202/post-133494

**Comment by silospen** [comment]
PR in case you're interested in the changes https://github.com/GoMule/GoMule/pull/9

**Comment by ajgringo619** [comment]
Working great!
